### PR TITLE
fixes #66

### LINKED ISSUE #66: sportran-analysis fails without "-w <W>"
If I try to run `sportran-analysis` without a `-w` flag, I get the following error
```
> sportran-analysis --param-from-input-file-column Temp TEMPERATURE --param-from-input-file-column Volume VOLUME -k flux -t 5 --input-format table -u metal -r -c 2 --TSKIP 2 --output TCEPS.out -- tmp2.txt
.
.
.
Traceback (most recent call last):
  File "/home/cluster2/bernstei/.local/bin/sportran-analysis", line 8, in <module>
    sys.exit(main())
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/sportran/analysis.py", line 210, in main
    run_analysis(args)
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/sportran/analysis.py", line 476, in run_analysis
    outarray = np.c_[j.freqs_THz, j.psd, j.fpsd, j.logpsd, j.flogpsd]
  File "/home/Software/python/system/extra/lib64/python3.9/site-packages/numpy/lib/index_tricks.py", line 412, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 2 has size 1
```
From what I can tell the issue is that two of the arrays being passed to `np.c_`, `j.fpsd` and `j.flogpsd`, are `None`, so the concatenation fails.

If I add a `-w 1`, which sets a filter width and therefore creates `j.fpsd`, it doesn't fail here.  Note that with this example input it does fail later, but that's just because my example file is _very_ short.  With a reasonable length input it succeeds if and only if I pass a `-w` argument.

The example input file is attached.

[tmp2.txt](https://github.com/sissaschool/sportran/files/10116077/tmp2.txt)

### PR DESCRIPTION
**Pull request by rikigigi**
Added test for cli when the user doesn't ask for the filtering of the data with the moving average approach version updated to rc3

updated citation

### CODE REVIEW

**Review by sebaB003 — APPROVED** [review]

**Review by lorisercole — APPROVED** [review]
All good to me. It seems to work! Thanks

**Comment by bernstei** [comment]
Thanks.  Can I ask what your policy is about merging this change into main, and updating the pypi version to include it?  Do you typically do that quickly, so I can just wait a bit and then do `pip install --update`, or do I really need to switch to the develop branch to get it any time soon?

**Comment by rikigigi** [comment]
> 
you can try it with
`pip install git+https://github.com/sissaschool/sportran@develop`
I have to make some little changes before a new release, like fixing all the citations... next week, I think

**Comment by lorisercole** [comment]
Hi @bernstei! Since @rikigigi created a new version from this PR, I am going to do a release right away! You should already be able pull the update from PyPI.
Anyway, FYI normally the policy is that we merge new commits to the `develop` branch and once we reach a stable/tested state, we can merge it into `master` with a new version tag. This will trigger a GitHub action to publish the package to PyPI.

**Comment by lorisercole** [comment]
> > 
> 
> you can try it with `pip install git+https://github.com/sissaschool/sportran@develop` I have to make some little changes before a new release, like fixing all the citations... next week, I think

@rikigigi Just saw your message. Since you edited the version to `1.0.0rc3` I already did the release.
But what we should actually do is the final `1.0.0` release. For this I agree we still need to do some little commits, mainly on documentation.👍

**Pull request merged**
